### ISSUE TITLE
Toast para las validaciones

### ISSUE THREAD

**Issue by marlon-Castano** [millerbarahona/CuevanApp#4]
se requiere un Toast para las validacion, por favor hacerlas bien

**Comment by marlon-Castano** [comment]
![descarga](https://user-images.githubusercontent.com/69131728/158943586-bd4374b9-2084-4240-9f2f-8e5afc20e9e6.jpg)

**Comment by JulianSar18** [comment]
Los Toast ya se agregaron en la pantalla de register y login
![image](https://user-images.githubusercontent.com/56314037/158943615-981067af-23df-4d42-a3c1-05d898ce7b52.png)

**Comment by marlon-Castano** [comment]
@JulianSar18 si ah bueno
